### PR TITLE
Handle mir_window_type_decoration introduced in mir recently

### PR DESCRIPTION
**Pull request by z3ntu**
Needed when a version of mir is used after https://github.com/MirServer/mir/commit/fa7c6121c003aebc559fccd3dd820bf72709449b

### CODE REVIEW

**Comment by mariogrip** [comment]
Please note qtubuntu requires mir on mir mesa patches (https://github.com/ubports/mesa/blob/xenial_-_mir26/debian/patches/egl-platform-mir.patch). I would suggest going the wayland way for clients, same as we are going to do really soon on edge xenial. Bionic already has this done, but not focused on phones. 

In bionic qtubuntu is not used, only part we use is ubuntuappmenu, but we will separate ubuntuappmenu to its own module pretty soon.

**Comment by z3ntu** [comment]
I guess I packaged it because of
image
(which was probably incorrect)
I'll remove the package because I don't see any dependency in our packaging on that and will see what will happen :).
Still going to leave this open because it's still a valid change

**Comment by mariogrip** [comment]
Ah! Unity.Screens comes from qtmir :)

**Comment by mariogrip** [comment]
I have also separated and renamed ubuntuappmenu to its own module https://gitlab.com/ubports/core/qtunity-appmenutheme

**Comment by vanyasem** [comment]
@mariogrip is this thing on github?

**Review by dobey — APPROVED** [review]
Looks OK.

**Pull request merged**
